baseurl = "https://ify.netlify.app/"
languageCode = "en-us"
title = "Stanley space"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Notes"
    url = ""
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Project"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/stanleesocca"
    weight = 4
[[menu.main]]
    name = "CV"
    url = "files/NMOR STANLEY CV.pdf"
    weight = 5

[params]
    description = "Personal space for all things marine science"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "Time-Depth_profile.png"
    width = 50
    height = 50
    alt = "Logo"

